version: '3'

services:
    web1:
      build: ./web
      volumes:
          - ./web:/code_python
      ports:
          - "80:5000"
      links:
          - redis:redis
      command: python app.py
    redis:
        image: redis:5.0.4
        ports:
            - "6379:6379"
        volumes:
            - ./db-data:/data-python

volumes:
    db-data:
